parameters: {}
environment: {}
packages:
  - name: "default"
    environment: {}
    parameters: {}
    actions:
      - name: "default"
        main: ''
        runtime: 'go:default'
        environment: {}
        parameters: {}

