parameters: {}
environment: {}
packages:
  - name: "v1"
    environment: {}
    parameters: {}
    actions:
      - name: "metadata"
        main: ''
        runtime: 'go:default'
        environment: {}
        parameters: {}

