parameters: {}
environment: {}
packages:
  - name: "v1"
    environment: {}
    parameters: {}
    actions:
      - name: "metadata"
        main: ''
        runtime: 'go:default'
        environment:
          NETBOX_TOKEN: "${NETBOX_TOKEN}"
          NETBOX_HOST: "${NETBOX_HOST}"
        parameters: {}

